### PR TITLE
Feature/pre release

### PR DESCRIPTION
**Pull request by eruizgar**
I updated poms in master.

### CODE REVIEW

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by becaresss** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
